### ISSUE TITLE
[Feature request] retrieve recently updated content

### ISSUE THREAD

**Issue by gotson** [givka/bedetheque-scraper#1]
Hi,

do you think it would be possible to have a feature to retrieve content that was added/modified recently ?

This way it would be possible to run incremental batches at specific interval.

**Comment by givka** [comment]
Hello,

I don't think this information is available from the bedetheque website. 
There is this link: https://www.bedetheque.com/nouveautes but it only shows the new albums from the last two months, which doesn't answer your needs.
