### ISSUE TITLE
[Feature request] Include album estimation

### ISSUE THREAD

**Issue by bperel** [givka/bedetheque-scraper#4]
Thank for your this software.
Some albums include an estimation, like here for https://www.bedetheque.com/BD-Picsou-Magazine-Tome-1-Picsou-Magazine-N1-62260.html : 
![image](https://user-images.githubusercontent.com/1484692/91603326-161e1a00-e96d-11ea-9cfd-023521c49c31.png)

It would be nice to include this information in the `album` object ; even better if it can be exposed under the shape of a range (minimum and maximum estimation)

**Comment by givka** [comment]
Hello, thanks for the suggestion, this was added in version 2.9.0.
