### ISSUE TITLE
Empty album list for some series

### ISSUE THREAD

**Issue by bperel** [givka/bedetheque-scraper#7]
Some albums lists are shown empty. Example: https://www.bedetheque.com/serie-18476-BD-Super-Picsou-Geant-Suppl-Picsou-Magazine__10000.html

The problem seems to be related to a selector filter: [this line](https://github.com/givka/bedetheque-scraper/blob/master/lib/album.ts#L126) excludes non-empty text elements, which is the case here.

**Comment by givka** [comment]
This is due to a design choice. I wanted to retrieve only the albums created by the authors, not the integrals, the bis albums and so on..

I'll add them shortly, but this means I will need to change the `getAlbumNumber()` behaviour.

**Comment by givka** [comment]
This was done in 000f729cf83e680f66e720e0e2fccc084575c6db and added in v3.2.0

**Comment by bperel** [comment]
Great, thanks!
